project:
  type: website
  output-dir: docs

website:
  title: "Allison Fisher"
  navbar:
    title: "Allison Fisher"
    font-size: 3
    right:
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
      - icon: flower1
        url:  https://github.com/arfisher/zool710-intro-Allison-Fisher



format:
  html:
    theme: quartz
    toc: true
    font-family: Georgia, serif;
    font-size: 1.2em;
    fontcolor: white
    linkcolor: pink
