---
title: "About"
---
I am originally from Boulder, CO where in high school I first became interested in pursuing biology. I completed a science fair project about measuring growth and success rates of coral starters on different substrates. Check out the ongoing project page <https://www.raisingcoral.org/>. This was actually my first exposure to R as I used it to analyze my data and make figures for my poster. I was mostly just following the direction of the project mentors but still got to interact with the language.

I moved to Honolulu, HI to pursue a bachelor's of science in marine biology at UH Manoa but later chose to broaden my studies to include terrestrial life as well.

I began volunteer work in many different realms of science: native ecosystem restoration, horticulture/agriculture, museum collection management, and lab work involving sequencing of SARS-CoV-2 genomes, a brief stint in biochemistry, and microhylid frog phylogenetics (the latter being most prevalent). Check it out <https://butlerlab.org/research/asterophryinae-frogs/>!

Since completing my BS, I have been working as teaching assistant for two different biology undergrad courses and working on writing up my first publication!

---
